### ISSUE TITLE
How to draw figure for episode reward? 

### ISSUE THREAD

**Issue by gd-zhang** [MG2033/A2C#1]
In summary, I can only find reward for each environment. So I am supposed to average over all envs?

**Comment by MG2033** [comment]
No, averaging doesn't mean anything, because each agent acts independently of the other agents. So, at a time, one agent might be playing good during its episode, while another agent might be playing bad at the same time.

During test mode, set the number of environments to 1 instead of 4. Then, you'll obtain the episode reward for a single agent.

Hope it helps.

**Comment by MG2033** [comment]
Yes, if you average over all environments, you'll get the average training performance.

However, it's done automatically in Tensorboard using the smoothing factor.
